### ISSUE TITLE
Why backends are shuffled?

### ISSUE THREAD

**Issue by asiragusa** [airbnb/synapse#127]
Digging into the code I found out that the backend order is shuffled, instead of being consistent for every node. This is causing me troubles when balancing the requests via consistent hash.

See: https://github.com/airbnb/synapse/blob/master/lib/synapse/haproxy.rb#L665

**Comment by jolynch** [comment]
@asiragusa They are shuffled because of long lived clients and round robin load balancing. Imagine that Synapse restarts haproxy, and then all your clients reconnect to the same host (because round robin), this could be pretty bad for something like HAProxy.

Like I mention in the linked PR I am not against adding the capability for backends to be shuffled or not. Happy to accept a PR that adds that functionality.
