### ISSUE TITLE
Synapse and HAProxy seamless reloads

### ISSUE THREAD

**Issue by StephanErb** [airbnb/synapse#238]
Excuse me for abusing this issue tracker as way to ask a user question:

I am wondering if anyone has experience running synapse with the HAProxy seamless restart settings `server-state-file`, `load-server-state-from-file global` and the extended  reload command 
```
socat haproxy.sock - <<< 'show servers state' > haproxy.state
systemctl haproxy reload
```
 (For details, see https://github.com/haproxy/haproxy/blob/master/examples/seamless_reload.txt)

Are there any known issues using this features, given that synapse will re-configure haproxy immediately after re-launching? 

Beyond a few warnings due to different service ordering it appears to be working. However, I have recently noticed a few backends enter a state where they never exit the `DOWN` state even though they can be reached from the proxy host.  Before I dig deeper into HAProxy I would like to confirm that I am not doing something stupid here.
 
```
Jul 10 07:57:07 proxy1 haproxy-systemd-wrapper[5649]: haproxy-systemd-wrapper: re-executing on SIGUSR2.
Jul 10 07:57:07 proxy1 haproxy-systemd-wrapper[5649]: haproxy-systemd-wrapper: executing /usr/sbin/haproxy -f /var/lib/synapse/haproxy.cfg -p /run/haproxy.pid -Ds -sf 9990
Jul 10 07:57:07 proxy1 haproxy-systemd-wrapper[5649]: [WARNING] 190/075707 (31569) : can't find server '0_mesos-node1.example.org:31724' with id '2' in backend with id '4' or name 'foo2-service.example.orgg'
Jul 10 07:57:07 proxy1 haproxy[31569]: can't find server '0_mesos-node1.example.org:31724' with id '2' in backend with id '4' or name 'foo2-service.example.orgg'
Jul 10 07:57:07 proxy1 haproxy[31569]: can't find server '0_mesos-node1.example.org:31724' with id '2' in backend with id '4' or name 'foo2-service.example.orgg'
Jul 10 07:57:07 proxy1 haproxy-systemd-wrapper[5649]: [WARNING] 190/075707 (31569) : In backend 'foo1-service.example.org' (id: '5'): server ID mismatch: from server state file: '1', from running config 2
Jul 10 07:57:07 proxy1 haproxy[31569]: In backend 'foo1-service.example.org' (id: 5): server ID mismatch: from server state file: '1', from running config 2
Jul 10 07:57:07 proxy1 haproxy[31569]: In backend 'foo1-service.example.org' (id: 5): server ID mismatch: from server state file: '1', from running config 2
Jul 10 07:57:07 proxy1 haproxy-systemd-wrapper[5649]: [WARNING] 190/075707 (31569) : In backend 'foo1-service.example.org' (id: '5'): server ID mismatch: from server state file: '2', from running config 1
Jul 10 07:57:07 proxy1 haproxy[31569]: In backend 'foo1-service.example.org' (id: 5): server ID mismatch: from server state file: '2', from running config 1
Jul 10 07:57:07 proxy1 haproxy[31569]: In backend 'foo1-service.example.org' (id: 5): server ID mismatch: from server state file: '2', from running config 1
Jul 10 07:57:07 proxy1 haproxy[31569]: Proxy stats started.
```

**Comment by jolynch** [comment]
I'm actually just working on porting us to using this now heh. The warnings are because SmartStack by default shuffles servers (so that long living connections get distributed across your fleet), but you can configure that with the [``backend_order``](https://github.com/airbnb/synapse/#the-haproxy-section) option.

I'm not sure about the perma DOWN state, that seems like a bug in HAProxy's state file load mechanism. I'll dig into it to see if it's Synapse or HAProxy.

**Comment by StephanErb** [comment]
Thanks for the quick response. I was able to eliminate the warnings using `backend_order: asc`.

I have also noticed that I had a potential slightly dodgy haproxy config: `observe layer7 on-error mark-down` but not running with `option   httpchk`. Maybe this is triggering something strange. I will deploy this and report back if I can still observe the problem.

**Comment by jolynch** [comment]
@StephanErb 

Yea, this looks like a pretty nasty bug in HAProxy's server state file implementation. The issue is the [puid check](https://gist.github.com/jolynch/296bf6fadba601a490f41381155cef71#file-server-c-L27-L48). Synapse shuffles backends on every reload, so we're guaranteed to miss the ids, and when servers come and go, applying state from a previous server puid is just incorrect (it probably doesn't exist anymore).

For example if the backend server's (puid, id)'s are (shuffled because synapse does that):

```
1 srv2
2 srv1
3 srv3
```

let's say srv3 fails, so synapse downs it. kubernetes or w.e. starts up srv4 to replace it, triggering the following config to be written:

```
1 srv2
2 srv1
3 srv4
4 srv3
```

When haproxy loads the new config and tries to find srv4, it will fail by name, but [succeed by puid](https://gist.github.com/jolynch/296bf6fadba601a490f41381155cef71#file-server-c-L48) (by id) "find" puid 3 and set srv4 to DOWN because srv3 was DOWN before, even though srv4 is in fact up (it will also set srv4's host to be the address of srv3 ... which is hilariously wrong).

I think the only workaround I can see is not shuffling backends, but that is really bad for long lived connections because all your servers might connect to the same server first. It's also really annoying to me that the servers state uses the puid as the id and the id as the name ... like that's just confusing as all.

I'm going to ping the mailing list and see what Willy/Baptiste think...

**Comment by jolynch** [comment]
Even if we sort this is still broken:

Imagine a situation where we don't keep srv3 around, we just remove srv3 and add srv4 (e.g. srv3 failed and we added srv4):

```
1 srv1
2 srv2
3 srv3
```

to

```
1 srv1
2 srv2
3 srv4
```

The same bug triggers and we apply state from srv3 to srv4. This is no good.

**Comment by StephanErb** [comment]
Thanks a lot for the quick and thorough investigation. I guess I will have to disable this feature for now...

**Comment by jolynch** [comment]
@StephanErb so digging deeper this isn't as bad a bug as I thought, but it's broken. Basically if the order of servers ever change (in the case of shuffle always, in the case of sorted, whenever a server that is "lower" than the rest gets inserted), then we don't apply state from the previous config. I don't think though that we'd apply the state from an incorrect server.

So ... this still doesn't work very well. I think that ideally haproxy would apply the state if the names match regardless if the order was the same, but I think willy might disagree. I'm going to start a conversation on the mailing list and see what happens.

Just a clarifying question, were your servers DOWN or in MAINT?

**Comment by StephanErb** [comment]
In that particular example we expected 6 running server instances. The HAProxy listed 10 backends in total: 4 in MAINT, 3 UP, and 3 DOWN. The MAINT ones were left overs from previous runs that were still sticking around due to the synapse state TTL. For the DOWN ones HAProxy complained that it could not be able to establish a L4 connection. Neither restarting/reloading synapse or HAproxy fixed the issue. After wiping synapse state file the MAINT instances were gone (as expected). Only by wiping the HAProxy server-state-file I managed to transition the ones in DOWN to UP. 

The server instances in questions had been restarted (resulting in new host/port) dozens of time over the timespan of a few hours. They were all handling very long sessions (~200-300secs). 

I will have to try to reproduce the issue in isolation, but need to improve our monitoring beforehand.

**Comment by jolynch** [comment]
Hm, yea that is quite strange. DOWN means that synapse is not really involved (synapse only ever MAINTs things), so I think that points to something to do with HAProxy healthchecks. When I've seen this kind of issue in the past it's usually either been too infrequent healthchecks (with the HAProxy state file you'd persist those healthcheck results across reloads and wait another inter before checking again) or too low connection timeouts (clients fail to connect a L4 in time and timeout).

If you can get more logging from HAProxy (esp healthcheck transitions) that would help debugging, but some good starter questions are:

* what's your server inter, fastiner, downinter?
* what's your connection timeout (timeout connect)

**Comment by jolynch** [comment]
@StephanErb we've been using this in production for a few weeks now and things seem to work well.

For posterity, you want to upgrade to 0.14.7 and optionally set ``server_order_seed`` to e.g. the hash of each host's hostname or if you need more than 65k servers in a backend set ``max_server_id`` appropriately.

**Comment by StephanErb** [comment]
Awesome, thanks again!
